# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "hoe-mercurial", "~>1.4", :group => [:development, :test]
gem "hoe-deveiate", "~>0.6", :group => [:development, :test]
gem "hoe-highline", "~>0.2", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "rake-compiler", "~>0.9", :group => [:development, :test]
gem "rake-compiler-dock", "~>0.2", :group => [:development, :test]
gem "hoe", "~>3.12", :group => [:development, :test]
gem "hoe-bundler", "~>1.0", :group => [:development, :test]
gem "rspec", "~>3.0", :group => [:development, :test]

# vim: syntax=ruby
