# -*- ruby -*-

ec_txt, ec_def = *ARGV


def parse_catalog_rows(source)
	source.scan(/\{(.*?)\},/m).map { |record| parse_catalog_row(record.first) }
end

def parse_catalog_row(record)
	record.scan(/([a-z_]+)\s*=>\s*'((?:\\'|[^'])*)'/m).to_h.transform_values do |value|
		value.gsub("\\'", "'")
	end
end

File.open(ec_def, 'w') do |fd_def|
	fd_def.puts <<~EOCODE
		# frozen_string_literal: true
		#
		# #{ec_def} - Definition of PostgreSQL initial type OIDs and their names.
		#
		# WARNING: This file is autogenerated. Please edit #{__FILE__} !
		#
		#

		require 'pg' unless defined?( PG )"

		class PG::WellKnwonOids
			TYPENAMES_BY_OID = {
	EOCODE

	json_txt = File.read(ec_txt).gsub(/^#.*/, "")

	type_rows = parse_catalog_rows(json_txt).select { |row| row["oid"] && row["typname"] }
	type_rows.sort_by! { |row| row["oid"].to_i }

	type_rows.each do |type|
		fd_def.puts "\t\t#{type["oid"]} => #{type["typname"].inspect},"
		if type["array_type_oid"]
			fd_def.puts "\t\t#{type["array_type_oid"]} => #{("_" + type["typname"]).inspect},"
		end
	end

	fd_def.puts <<~EOCODE
			}.freeze
		end
	EOCODE
end
